### PR TITLE
Implemented some families

### PR DESCRIPTION
**Pull request by BadRyuner**
I'll try to add more families this weekend, so DRAFT PR.

### CODE REVIEW

**Comment by BadRyuner** [comment]
Advanced Simd is very cursed.

**Comment by BadRyuner** [comment]
I should add tests for new instructions?

**Comment by SamboyCoding** [comment]
Ideally yes, everything newly added should be verified with some test disassembly.

**Comment by SamboyCoding** [comment]
I had however missed that this PR was no longer a draft so I could just merge and do the tests myself

**Comment by SamboyCoding** [comment]
Tests done for everything up to and including Arm64Branches.cs in the first table above. Last 2 files not tested yet. Did uncover a couple minor issues but fixed those and they're now covered by tests.

**Comment by SamboyCoding** [comment]
NB The "three same" you implemented was actually "Advanced SIMD Three Same" which was already implemented. The correct section to be included in that function is "Advanced SIMD Scalar Three Same"

**Pull request merged**
